# Generated by Django 4.2.4 on 2023-08-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datainput', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancer_type', models.CharField(max_length=100)),
                ('stage', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('lifestyle_factors', models.TextField()),
                ('treatment_type', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField()),
                ('frequency', models.PositiveIntegerField()),
                ('medication_names', models.TextField()),
                ('treatment_outcome', models.TextField()),
                ('direct_costs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('indirect_costs', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
