# Generated by Django 4.2.4 on 2023-08-20 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datainput', '0002_cancerdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CancerData',
        ),
    ]
