# Generated by Django 4.2.4 on 2023-08-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datainput', '0006_alter_patientdata_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='stage',
            field=models.CharField(choices=[('Stage1', 'Stage 1'), ('Stage2', 'Stage 2'), ('Stage3', 'Stage 3'), ('Stage4', 'Stage 4')], max_length=50),
        ),
    ]
