# Generated by Django 4.2.4 on 2023-08-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datainput', '0007_alter_patientdata_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdata',
            name='mobile',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='patientdata',
            unique_together={('name', 'mobile', 'gender', 'age')},
        ),
    ]
